name: Package Chrome Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          mkdir -p packaged_extension
          cp -r extension/* packaged_extension/
          zip -r x-solana-token-info.zip packaged_extension -x '*.git*' '*.github*' 'node_modules/*'

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: x-solana-token-info
          path: x-solana-token-info.zip

      - name: (Optional) Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: x-solana-token-info.zip
